[package]
name = "keyless-crypto"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
expander_compiler = { git = "https://github.com/akuya-ekorot/ExpanderCompilerCollection", branch = "master" }
serde = { version = "1.0.217", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"

[dependencies.wasm-bindgen]
version = "0.2.100"
features = ["serde-serialize"]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
